POST http://localhost:8080/chart
Content-Type: application/json
{
	"title": "DISCOVERY 750W AJU - CHILLER - OUTLET",
	"subTitle": "DISPERSÃO DE TEMPERATURA",
	"presetMin": 20,
	"presetMax": 25,
	"minimoHistorico": 21,
	"maximoHistorico": 22,
	"textLegend": "Temperatura (°C)",
	"marcadorx": 1730505960000,
	"marcadory": 23.8,
	"marcadorLabel": "°C",
    "series": [
        [
            1730505632000,
            23.6
        ],
        [
            1730505661000,
            23.7
        ],
        [
            1730505720000,
            23.7
        ],
        [
            1730505780000,
            23.7
        ],
        [
            1730505841000,
            23.8
        ],
        [
            1730505901000,
            23.8
        ],
        [
            1730505960000,
            23.8
        ],
        [
            1730506021000,
            23.9
        ],
        [
            1730506080000,
            23.9
        ],
        [
            1730506140000,
            23.9
        ],
        [
            1730506201000,
            23.9
        ],
        [
            1730506261000,
            24
        ],
        [
            1730506320000,
            24
        ],
        [
            1730506380000,
            24
        ],
        [
            1730506440000,
            24
        ],
        [
            1730506501000,
            24.1
        ],
        [
            1730506561000,
            24.1
        ],
        [
            1730506620000,
            24.1
        ],
        [
            1730506680000,
            24.1
        ],
        [
            1730506741000,
            24.2
        ],
        [
            1730506800000,
            24.2
        ],
        [
            1730506860000,
            24.2
        ],
        [
            1730506921000,
            24.2
        ],
        [
            1730506981000,
            24.2
        ],
        [
            1730507040000,
            24.2
        ],
        [
            1730507100000,
            24.2
        ],
        [
            1730507161000,
            24.2
        ],
        [
            1730507221000,
            24.2
        ],
        [
            1730507280000,
            24.3
        ],
        [
            1730507340000,
            24.3
        ],
        [
            1730507401000,
            24.3
        ],
        [
            1730507461000,
            24.3
        ],
        [
            1730507520000,
            24.4
        ],
        [
            1730507580000,
            24.4
        ],
        [
            1730507640000,
            24.4
        ],
        [
            1730507700000,
            24.4
        ],
        [
            1730507761000,
            24.4
        ],
        [
            1730507821000,
            24.4
        ],
        [
            1730507880000,
            24.5
        ],
        [
            1730507940000,
            24.5
        ],
        [
            1730508001000,
            24.5
        ],
        [
            1730508061000,
            24.5
        ],
        [
            1730508120000,
            24.5
        ],
        [
            1730508180000,
            24.5
        ],
        [
            1730508240000,
            24.5
        ],
        [
            1730508300000,
            24.5
        ],
        [
            1730508360000,
            24.5
        ],
        [
            1730508421000,
            24.6
        ],
        [
            1730508480000,
            24.6
        ],
        [
            1730508540000,
            24.6
        ],
        [
            1730508601000,
            24.6
        ],
        [
            1730508661000,
            24.6
        ],
        [
            1730508720000,
            24.6
        ],
        [
            1730508780000,
            24.6
        ],
        [
            1730508900000,
            24.7
        ],
        [
            1730508960000,
            24.7
        ],
        [
            1730509021000,
            24.7
        ],
        [
            1730509080000,
            24.7
        ],
        [
            1730509140000,
            24.7
        ],
        [
            1730509201000,
            24.7
        ],
        [
            1730509261000,
            24.7
        ],
        [
            1730509320000,
            24.7
        ],
        [
            1730509380000,
            24.7
        ],
        [
            1730509457000,
            24.7
        ],
        [
            1730509500000,
            24.7
        ],
        [
            1730509560000,
            24.7
        ]
    ]
}